language: python

python:
  - "3.4"

sudo: false

before_install:
  - pip install flake8
  - pip install coveralls
  - pip install django
  - pip install python-dateutil
  - pip install pandas==0.18.1
  - pip install sortinghat
  - cd django_hatstall && python manage.py makemigrations && cd ..
  - cd django_hatstall && python manage.py migrate && cd ..

# install:
#   - ./setup.py install

script:
  - flake8 django_hatstall
  - cd django_hatstall && python manage.py test && cd ..
