elasticsearch:
  image: bitergia/elasticsearch:5.6.0
  command: /elasticsearch/bin/elasticsearch -E network.bind_host=0.0.0.0
  ports:
    - "9200:9200"
  environment:
    - ES_JAVA_OPTS=-Xms2g -Xmx2g

kibiter:
  image: bitergia/kibiter:5.6.0
  links:
    - elasticsearch
  ports:
   - "5601:5601"
  environment:
    - ELASTICSEARCH_USER=bitergia
    - ELASTICSEARCH_PASSWORD=bitergia
    - PROJECT_NAME=Test20
    - NODE_OPTIONS=--max-old-space-size=1000

redis:
  image: redis:latest
  command: redis-server --save "" --appendonly no

mordred:
  image: bitergia/mordred:elasticgirl.28
  links:
    - elasticsearch
    - kibiter
    - mariadb
    - redis
  volumes:
    - .:/home/grimoirelab/conf
    - ./logs:/home/grimoirelab/logs

mariadb:
    image: mariadb:10.0
    environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes

hatstall:
  image: acsdocker/hatstall
  links: 
        - mariadb
  ports:
        - 8000:8000
  # volumes:
    # - ./stage:/home/meditor/stage
